version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: accountmanager_chromadb
    ports:
      - "${CHROMA_PORT:-8001}:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    volumes:
      - chromadb_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - accountmanager_network

volumes:
  chromadb_data:
    driver: local

networks:
  accountmanager_network:
    driver: bridge
    name: accountmanager_network 